### findall
http://localhost:8089/users
### findall-container
http://localhost:8079/users
### findall-vm
http://naekaracubae.msyhu.com:8089/users
### findall-ec2
http://3.38.35.79:8089/users

### count
https://localhost:8089/users/count
### count vm
http://naekaracubae.msyhu.com:8089/users/count

### saveUser
POST http://localhost:8089/users
Content-Type: application/json

{"name": "Mario", "email": "mario@msyhu.com"}

### saveUser-ec2
POST http://3.38.35.79:8089/users
Content-Type: application/json

{"name": "Mario", "email": "mario@msyhu.com"}

### delete
DELETE http://localhost:8089/users/6

### existsemail
http://localhost:8089/users/exists/mario@msyhu.com

### updateUser
PUT http://localhost:8089/users/3
Content-Type: application/json

{"name": "Mario", "email": "mario@msyhu.com"}

